### ISSUE TITLE
ERC1155 too large?

### ISSUE THREAD

**Issue by vicpon** [rarible/protocol-contracts#167]
Hi, I created a simple contract that inherits from ERC1155Rarible. I'm using hardhat to create tests for it. When my test deploys the contract to the HRE (Hardhat Runtime Environment), I get this error:

```shell
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Transaction reverted: trying to deploy a contract whose code is too large", method="estimateGas", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","data":"0x6...","accessList":null}, error={"stackTrace":[{"type":21,"sourceReference":{"sourceName":"contracts/MyNftUpgradeable.sol","sourceContent":"// SPDX-License-Identifier: MIT\r\npragma solidity ^0.7.6;\r\npragma abicoder v2;\r\n\r\n// import \"@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol\";\r\n//Ownable is needed to setup sales royalties on Open Sea\r\n//if you are the owner of the contract you can configure sales Royalties in the Open Sea website\r\n// import \"@openzeppelin/contracts/access/Ownable.sol\";\r\n//the rarible dependency files are needed to setup sales royalties on Rarible\r\n// import \"rarible/royalties/contracts/impl/RoyaltiesV2Impl.sol\";\r\nimport \"@rarible/tokens/contracts/erc-1155/ERC1155Rarible.sol\";\r\n\r\ncontract MyNftUpgradeable is ERC1155Rarible {\r\n    \r\n}\r\n","contract":"MyNftUpgradeable","function":"constructor","line":13,"range":[590,651]}}],"data":"0x"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)
      at Logger.makeError (node_modules\@ethersproject\logger\src.ts\index.ts:261:28)
      at Logger.throwError (node_modules\@ethersproject\logger\src.ts\index.ts:273:20)
      at checkError (node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:78:20)
      at EthersProviderWrapper.<anonymous> (node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:603:20)
      at step (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
      at Object.throw (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
      at rejected (node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
```

This is my contract:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.6;
pragma abicoder v2;

import "@rarible/tokens/contracts/erc-1155/ERC1155Rarible.sol";

contract MyNftUpgradeable is ERC1155Rarible {
    
}
```

Judging from the stack trace, it doesn't seem to be a hardhat error. Since this contract is already deployed on mainnet, I think it's probably a configuration error. Any tips?

**Comment by vicpon** [comment]
Added `allowUnlimitedContractSize: true` to the hardhat network configuration and error is gone (for now)
