### ISSUE TITLE
Bug: undefined parameters number in project tokens/ 

### ISSUE THREAD

**Issue by SKonstantinS** [rarible/protocol-contracts#64]
Run:
cd tokens/
truffle test
Detect errors 
 1) Contract: ERC1155Rarible
       mint and transfer by minter, token create by Factory:
     Error: Invalid number of parameters for "undefined". Got 1 expected 3!
      at Context.<anonymous> (test/erc-1155/ERC1155Rarible.test.js:29:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Contract: ERC721Rarible
       mint and transfer by minter, and token created by ERC721Factory :
     Error: Invalid number of parameters for "undefined". Got 1 expected 3!
      at Context.<anonymous> (test/erc-721/Rarible.test.js:36:38)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by SKonstantinS** [comment]
https://github.com/rarible/protocol-contracts/pull/50/commits/eb4bf500a9053d56ceb3c0a30ba6cea4169a838f
DONE

**Comment by SKonstantinS** [comment]
Close, because done
